name: Release

# Triggers:
# - Push tags (v*): Build cross-platform binaries and create GitHub release
# - Pull requests: Build cross-platform binaries only (no release) to verify builds work

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    # Builds cross-platform binaries for Windows, Linux, and macOS
    # For tags: Creates GitHub release with binaries
    # For PRs: Just builds and uploads artifacts for testing
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            runtime: linux-x64
            artifact: ddns-hetzner-linux-x64.tar.gz
          - os: windows-latest
            runtime: win-x64
            artifact: ddns-hetzner-win-x64.zip
          - os: macos-latest
            runtime: osx-x64
            artifact: ddns-hetzner-osx-x64.tar.gz
    
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore ddns-hetzner.csproj

      - name: Build and publish
        run: dotnet publish ddns-hetzner.csproj -c Release -r ${{ matrix.runtime }} --self-contained true -o ./publish

      - name: Create archive (Linux/macOS)
        if: matrix.os != 'windows-latest'
        run: tar -czf ${{ matrix.artifact }} -C ./publish .

      - name: Create archive (Windows)
        if: matrix.os == 'windows-latest'
        run: Compress-Archive -Path ./publish/* -DestinationPath ${{ matrix.artifact }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: ${{ matrix.artifact }}
          retention-days: ${{ github.event_name == 'pull_request' && 7 || 30 }}

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Move artifacts to root
        run: |
          find ./artifacts -type f \( -name "*.tar.gz" -o -name "*.zip" \) -exec mv {} . \;
          ls -la *.tar.gz *.zip

      - name: Extract tag name
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: Release ${{ env.TAG_NAME }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            ddns-hetzner-win-x64.zip
            ddns-hetzner-linux-x64.tar.gz
            ddns-hetzner-osx-x64.tar.gz